<html>
  <head>
    <title>python-django3 Info</title>
  </head>
  <body>
  <h1>python-django3 Info</h1>
    <p>
      python-django3 was added to epel8 repo on 2024-10-02
      <br>Page updated: 2024-10-02 19:34
      <br><a href="../status-repo.html">Repo Status</a> -
      <a href="../../status-overall.html">Overall Status</a>
    </p>

    <p>
      Source NVR: <b>python-django3-3.2.20-1.el8</b> (2024-10-02)
    </p>

    <h2>Binary Packages</h2>
    <table border=0>
      <tr>
          <td>python-django3-bash-completion</td>
          <td><b>python-django3-bash-completion-3.2.20-1.el8</b></td>
        </tr>
      <tr>
          <td>python3-django3</td>
          <td><b>python3-django3-3.2.20-1.el8</b></td>
        </tr>
      </table>

    <h2>Bugs</h2>
    <table border=1>
      <tr>
          <td><a href="https://bugzilla.redhat.com/show_bug.cgi?id=2242180">2242180</a></td>
          <td>NEW</td>
          <td>CVE-2023-43665 python-django3: python-django: Denial-of-service possibility in django.utils.text.Truncator [epel-8]</td>
        </tr>
      <tr>
          <td><a href="https://bugzilla.redhat.com/show_bug.cgi?id=2252960">2252960</a></td>
          <td>NEW</td>
          <td>Handle correctly 'NO FOUND' in memached delete method</td>
        </tr>
      <tr>
          <td><a href="https://bugzilla.redhat.com/show_bug.cgi?id=2314486">2314486</a></td>
          <td>NEW</td>
          <td>CVE-2024-45230 python-django3: Potential denial-of-service vulnerability in django.utils.html.urlize() [epel-all]</td>
        </tr>
      </table>

    <h2>Install Failures</h2>
      </body>
</html>